import { statementEngine } from '@/lib/statement-engine'

const brl=(n:number)=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0})
export default function DemonstracoesIntegradas(){
 const e=statementEngine(); const {totals}=e
 const resultado=totals.receitas-totals.custos-totals.despesas
 return <main className="content" style={{marginLeft:0,width:'100%',maxWidth:1400,margin:'0 auto'}}><header><div><small>MOTOR CONTÁBIL V5</small><h1>Demonstrações Integradas</h1><p>Resultado calculado a partir do Razão + Mapeamento Contábil</p></div><div className="period">Modelo 2026</div></header>
 <div className="cards"><div className="card"><span>Ativo</span><strong>{brl(totals.ativo)}</strong><small>Balancete</small></div><div className="card"><span>Passivo</span><strong>{brl(totals.passivo)}</strong><small>Balancete</small></div><div className="card"><span>Patrimônio Líquido</span><strong>{brl(totals.patrimonio)}</strong><small>Balancete</small></div><div className="card"><span>Resultado</span><strong>{brl(resultado)}</strong><small>DRE calculada</small></div></div>
 <div className="grid"><section className="panel"><div className="panel-title"><h2>Balanço Patrimonial</h2><span>Origem: Razão</span></div><div className="rows"><div className="row"><span>Ativo</span><b>{brl(totals.ativo)}</b></div><div className="row"><span>Passivo</span><b>{brl(totals.passivo)}</b></div><div className="row"><span>Patrimônio Líquido</span><b>{brl(totals.patrimonio)}</b></div><div className="row"><span>Passivo + PL</span><b>{brl(totals.passivo+totals.patrimonio)}</b></div></div></section><section className="panel"><div className="panel-title"><h2>DRE</h2><span>Competência</span></div><div className="rows"><div className="row"><span>Receitas</span><b>{brl(totals.receitas)}</b></div><div className="row"><span>Custos</span><b>{brl(totals.custos)}</b></div><div className="row"><span>Despesas</span><b>{brl(totals.despesas)}</b></div><div className="row"><span>Resultado</span><b>{brl(resultado)}</b></div></div></section></div>
 <section className="panel"><div className="panel-title"><h2>Controle de integração</h2><span>{Math.abs(totals.ativo-(totals.passivo+totals.patrimonio))<0.01?'✓ OK':'! Revisar'}</span></div><div className="note">As demonstrações desta tela não usam os valores fixos da visão antiga. Elas são calculadas a partir do <strong>Razão</strong>, usando o <strong>Mapeamento Contábil</strong>. O próximo passo é integrar essa mesma origem à DFC e substituir progressivamente os demonstrativos antigos.</div></section></main>
}
