'use client'
import {useEffect,useMemo,useState} from 'react'
import {statementEngine} from '@/lib/statement-engine'
import {financialEntriesToJournal} from '@/lib/financial-accounting-integration'
import {readFinancialSource} from '@/lib/financial-source'
import {initialEntries,type FinancialEntry} from '@/lib/lancamentos-data'
import {chartOfAccounts,type JournalEntry} from '@/lib/accounting-core'

const brl=(n:number)=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0})
const pct=(n:number)=>`${n.toFixed(1).replace('.',',')}%`
const MONTHS=Array.from({length:12},(_,i)=>`2026-${String(i+1).padStart(2,'0')}`)
const ML=['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez']
type M={revenue:number;costs:number;opex:number;fin:number;gross:number;op:number;net:number}
type Row={code:string;name:string;value:number;children:Row[]}
type View='mensal'|'orcado'|'comparativo'
const empty=():M=>({revenue:0,costs:0,opex:0,fin:0,gross:0,op:0,net:0})
const sum=(a:M,b:M):M=>({revenue:a.revenue+b.revenue,costs:a.costs+b.costs,opex:a.opex+b.opex,fin:a.fin+b.fin,gross:a.gross+b.gross,op:a.op+b.op,net:a.net+b.net})

export default function DREGerencial(){
 const[entries,setEntries]=useState<FinancialEntry[]>(initialEntries),[errors,setErrors]=useState<string[]>([]),[expanded,setExpanded]=useState<Set<string>>(new Set()),[month,setMonth]=useState('2026-02'),[view,setView]=useState<View>('mensal')
 useEffect(()=>{const s=readFinancialSource();setEntries(s.entries);setErrors(s.errors)},[])
 const journal=useMemo(()=>financialEntriesToJournal(entries),[entries])
 const data=useMemo(()=>monthly(journal.entries),[journal.entries])
 const selected=data.get(month)||empty(), selectedJournal=journal.entries.filter(e=>e.competence===month)
 const statement=useMemo(()=>statementEngine(selectedJournal),[selectedJournal])
 const balances=useMemo(()=>new Map(statement.dre.map(r=>[r.code,r.balance])),[statement])
 const groups=useMemo(()=>hierarchy(balances),[balances])
 const annual=useMemo(()=>MONTHS.reduce((a,m)=>sum(a,data.get(m)||empty()),empty()),[data])
 const mi=Number(month.slice(5))-1
 const toggle=(code:string)=>setExpanded(p=>{const n=new Set(p);n.has(code)?n.delete(code):n.add(code);return n})
 const expandAll=()=>setExpanded(new Set(groups.flatMap(r=>[r.code,...r.children.map(c=>c.code)])))
 return <main className="content" style={{marginLeft:0,width:'100%',maxWidth:1450,margin:'0 auto'}}>
  <header><div><small>CONTROLADORIA FINANCEIRA</small><h1>DRE Gerencial</h1><p>Demonstração mensal • Orçado × Realizado • Regime de competência</p></div><div style={{display:'grid',gap:6,justifyItems:'end'}}><span style={{fontSize:10,color:'#718098'}}>MÊS EM ANÁLISE</span><select value={month} onChange={e=>{setMonth(e.target.value);setExpanded(new Set())}} style={selectStyle}>{MONTHS.map((m,i)=><option value={m} key={m}>{ML[i]}/2026</option>)}</select></div></header>
  <div className="bp-tabs" style={{marginBottom:18}}><button className={view==='mensal'?'active':''} onClick={()=>setView('mensal')}>DRE Mensal</button><button className={view==='orcado'?'active':''} onClick={()=>setView('orcado')}>Orçado × Realizado</button><button className={view==='comparativo'?'active':''} onClick={()=>setView('comparativo')}>Análise Comparativa</button></div>
  <div className="cards"><Card title="Receita Líquida" value={selected.revenue} sub={`${ML[mi]}/2026`}/><Card title="Lucro Bruto" value={selected.gross} sub={`Margem ${pct(selected.revenue?selected.gross/selected.revenue*100:0)}`}/><Card title="Resultado Operacional" value={selected.op} sub={`Margem ${pct(selected.revenue?selected.op/selected.revenue*100:0)}`}/><Card title="Lucro Líquido" value={selected.net} sub={`Margem ${pct(selected.revenue?selected.net/selected.revenue*100:0)}`}/></div>
  {view==='mensal'&&<MonthlyView data={data} journal={journal.entries} groups={groups} month={month} expanded={expanded} toggle={toggle} expandAll={()=>expandAll()} collapseAll={()=>setExpanded(new Set())}/>} 
  {view==='orcado'&&<BudgetView data={data} annual={annual}/>} 
  {view==='comparativo'&&<CompareView data={data} annual={annual}/>} 
  {(errors.length||journal.errors.length)>0&&<div className="note" style={{marginTop:10,borderLeft:'4px solid #d92d20'}}><strong>Atenção:</strong> {[...errors,...journal.errors].join(' ')}</div>}
 </main>
}

function MonthlyView({data,journal,groups,month,expanded,toggle,expandAll,collapseAll}:{data:Map<string,M>;journal:JournalEntry[];groups:Row[];month:string;expanded:Set<string>;toggle:(c:string)=>void;expandAll:()=>void;collapseAll:()=>void}){return <section className="panel wide"><div className="panel-title"><div><h2>DRE mensal — visão hierárquica</h2><span>+ expande • − recolhe • detalhe do mês selecionado</span></div><span>Origem: Base financeira → Diário → Razão → Mapeamento Contábil</span></div><div style={{display:'flex',gap:8,marginBottom:12}}><button type="button" onClick={expandAll} style={buttonStyle}>Expandir contas</button><button type="button" onClick={collapseAll} style={buttonStyle}>Recolher</button></div><div className="table-wrap" style={{overflowX:'auto'}}><table className="dre-table" style={{minWidth:1050}}><thead><tr><th style={{textAlign:'left',minWidth:230}}>Conta</th>{ML.map(m=><th key={m}>{m}</th>)}<th>Total</th></tr></thead><tbody><Section label="Receita Líquida" values={MONTHS.map(m=>data.get(m)?.revenue||0)}/>{groups.filter(r=>r.code.startsWith('4')).map(r=><Drill key={r.code} row={r} journal={journal} selectedMonth={month} negative={false} expanded={expanded} toggle={toggle}/>)}<Section label="= Lucro Bruto" values={MONTHS.map(m=>data.get(m)?.gross||0)} total/><Section label="(-) Custos" values={MONTHS.map(m=>-(data.get(m)?.costs||0))}/>{groups.filter(r=>r.code.startsWith('5')).map(r=><Drill key={r.code} row={r} journal={journal} selectedMonth={month} negative expanded={expanded} toggle={toggle}/>)}<Section label="(-) Despesas Operacionais" values={MONTHS.map(m=>-(data.get(m)?.opex||0))}/>{groups.filter(r=>r.code.startsWith('6.1')).map(r=><Drill key={r.code} row={r} journal={journal} selectedMonth={month} negative expanded={expanded} toggle={toggle}/>)}<Section label="= Resultado Operacional" values={MONTHS.map(m=>data.get(m)?.op||0)} total/><Section label="Resultado Financeiro" values={MONTHS.map(m=>-(data.get(m)?.fin||0))}/>{groups.filter(r=>r.code.startsWith('6.2')).map(r=><Drill key={r.code} row={r} journal={journal} selectedMonth={month} negative expanded={expanded} toggle={toggle}/>)}<Section label="= Lucro Líquido" values={MONTHS.map(m=>data.get(m)?.net||0)} total/></tbody></table></div><div className="note" style={{marginTop:14}}>O Total soma o exercício. Ao expandir, o detalhe dos lançamentos considera o mês selecionado.</div></section>}

function Drill({row,journal,selectedMonth,negative,expanded,toggle}:{row:Row;journal:JournalEntry[];selectedMonth:string;negative:boolean;expanded:Set<string>;toggle:(c:string)=>void}){const open=expanded.has(row.code),values=MONTHS.map(m=>accountValue(journal,m,row.code,negative)),total=values.reduce((a,b)=>a+b,0),movements=journal.filter(e=>e.competence===selectedMonth&&e.lines.some(l=>l.account===row.code));return <><tr className="group-row" onClick={()=>toggle(row.code)} style={{cursor:'pointer'}}><td><Icon open={open} click={()=>toggle(row.code)} label={row.name}/><strong>{row.code} — {row.name}</strong></td>{values.map((v,i)=><td className="amount" key={MONTHS[i]}>{brl(v)}</td>)}<td className="amount"><strong>{brl(total)}</strong></td></tr>{open&&row.children.length>0&&row.children.map(c=><Child key={c.code} row={c} journal={journal} selectedMonth={selectedMonth} negative={negative} expanded={expanded} toggle={toggle}/>)}{open&&row.children.length===0&&movements.map(e=><Movement key={`${row.code}-${e.id}`} entry={e} code={row.code} negative={negative}/>)}</>}
function Child({row,journal,selectedMonth,negative,expanded,toggle}:{row:Row;journal:JournalEntry[];selectedMonth:string;negative:boolean;expanded:Set<string>;toggle:(c:string)=>void}){const open=expanded.has(row.code),values=MONTHS.map(m=>accountValue(journal,m,row.code,negative)),total=values.reduce((a,b)=>a+b,0),movements=journal.filter(e=>e.competence===selectedMonth&&e.lines.some(l=>l.account===row.code));return <><tr className="item-row" onClick={()=>toggle(row.code)} style={{cursor:'pointer',background:'#fafbfc'}}><td style={{paddingLeft:30}}><Icon open={open} click={()=>toggle(row.code)} label={row.name}/>↳ {row.code} — {row.name}</td>{values.map((v,i)=><td className="amount" key={MONTHS[i]}>{brl(v)}</td>)}<td className="amount">{brl(total)}</td></tr>{open&&movements.map(e=><Movement key={`${row.code}-${e.id}`} entry={e} code={row.code} negative={negative}/>)}</>}
function Icon({open,click,label}:{open:boolean;click:()=>void;label:string}){return <button type="button" className="expand-btn" aria-label={open?`Recolher ${label}`:`Expandir ${label}`} onClick={e=>{e.stopPropagation();click()}}>{open?'−':'+'}</button>}
function Movement({entry,code,negative}:{entry:JournalEntry;code:string;negative:boolean}){const line=entry.lines.find(l=>l.account===code);if(!line)return null;const raw=line.debit-line.credit,value=negative?-Math.abs(raw):-raw;return <tr style={{background:'#f6f8fb',fontSize:12}}><td style={{paddingLeft:70,color:'#475467'}}>↳ {entry.date} • {entry.description}{entry.document?` • Doc. ${entry.document}`:''}{entry.costCenter?` • CC ${entry.costCenter}`:''}</td>{MONTHS.map(m=><td className="amount" key={m}>{m===entry.competence?brl(value):'—'}</td>)}<td className="amount">{brl(value)}</td></tr>}
function accountValue(journal:JournalEntry[],month:string,code:string,negative:boolean){const s=statementEngine(journal.filter(e=>e.competence===month)),v=s.dre.find(r=>r.code===code)?.balance||0;return negative?-Math.abs(v):Math.abs(v)}
function hierarchy(b:Map<string,number>):Row[]{return chartOfAccounts.filter(a=>a.level===2&&['4','5','6'].includes(a.parentCode||'')).map(a=>({code:a.code,name:a.name,value:b.get(a.code)||0,children:chartOfAccounts.filter(c=>c.parentCode===a.code&&c.level===3).map(c=>({code:c.code,name:c.name,value:b.get(c.code)||0,children:[]}))}))}
function monthly(journal:JournalEntry[]){const out=new Map<string,M>();for(const m of MONTHS){const s=statementEngine(journal.filter(e=>e.competence===m)),revenue=s.totals.receitas,costs=s.totals.custos,opex=s.dre.filter(r=>r.class==='despesa'&&r.code.startsWith('6.1')).reduce((a,r)=>a+r.balance,0),fin=s.dre.filter(r=>r.class==='despesa'&&r.code.startsWith('6.2')).reduce((a,r)=>a+r.balance,0),gross=revenue-costs,op=gross-opex;out.set(m,{revenue,costs,opex,fin,gross,op,net:op-fin})}return out}
function Section({label,values,total=false}:{label:string;values:number[];total?:boolean}){return <tr className={total?'total':''}><td><b>{label}</b></td>{values.map((v,i)=><td className="amount" key={MONTHS[i]}><b>{brl(v)}</b></td>)}<td className="amount"><b>{brl(values.reduce((a,b)=>a+b,0))}</b></td></tr>}

function BudgetView({data,annual}:{data:Map<string,M>;annual:M}){return <section className="panel wide"><div className="panel-title"><div><h2>Orçado × Realizado — visão mensal</h2><span>Comparação por mês e total do exercício</span></div><span>Orçamento demonstrativo</span></div><div className="table-wrap" style={{overflowX:'auto'}}><table className="dre-table" style={{minWidth:900}}><thead><tr><th style={{textAlign:'left'}}>Mês</th><th>Receita Orçada</th><th>Receita Realizada</th><th>Var. R$</th><th>Var. %</th><th>Resultado Operacional</th></tr></thead><tbody>{MONTHS.map((m,i)=>{const d=data.get(m)||empty(),b=d.revenue*.98;return <BudgetRow key={m} label={ML[i]} budget={b} actual={d.revenue} op={d.op}/>})}<BudgetRow label="TOTAL 2026" budget={annual.revenue*.98} actual={annual.revenue} op={annual.op} total/></tbody></table></div><div className="note" style={{marginTop:14}}>O orçamento desta etapa é apenas demonstrativo. A estrutura está preparada para receber uma base orçamentária oficial por conta, centro de custo e mês.</div></section>}
function BudgetRow({label,budget,actual,op,total=false}:{label:string;budget:number;actual:number;op:number;total?:boolean}){const v=actual-budget;return <tr className={total?'total':''}><td><strong>{label}</strong></td><td className="amount">{brl(budget)}</td><td className="amount">{brl(actual)}</td><td className="amount">{brl(v)}</td><td className="amount">{pct(budget?v/budget*100:0)}</td><td className="amount">{brl(op)}</td></tr>}
function CompareView({data,annual}:{data:Map<string,M>;annual:M}){return <section className="panel wide"><div className="panel-title"><div><h2>Análise Comparativa</h2><span>Evolução mensal dos principais indicadores</span></div><span>Base histórica anterior ainda não cadastrada</span></div><div className="table-wrap" style={{overflowX:'auto'}}><table className="dre-table" style={{minWidth:900}}><thead><tr><th style={{textAlign:'left'}}>Mês</th><th>Receita</th><th>Margem Bruta</th><th>Margem Operacional</th><th>Margem Líquida</th><th>Resultado Operacional</th></tr></thead><tbody>{MONTHS.map((m,i)=>{const d=data.get(m)||empty();return <tr key={m}><td><strong>{ML[i]}/2026</strong></td><td className="amount">{brl(d.revenue)}</td><td className="amount">{pct(d.revenue?d.gross/d.revenue*100:0)}</td><td className="amount">{pct(d.revenue?d.op/d.revenue*100:0)}</td><td className="amount">{pct(d.revenue?d.net/d.revenue*100:0)}</td><td className="amount">{brl(d.op)}</td></tr>})}<tr className="total"><td>TOTAL 2026</td><td className="amount">{brl(annual.revenue)}</td><td className="amount">{pct(annual.revenue?annual.gross/annual.revenue*100:0)}</td><td className="amount">{pct(annual.revenue?annual.op/annual.revenue*100:0)}</td><td className="amount">{pct(annual.revenue?annual.net/annual.revenue*100:0)}</td><td className="amount">{brl(annual.op)}</td></tr></tbody></table></div><div className="note" style={{marginTop:14}}>A comparação com 2025 ficará disponível quando a base histórica for carregada; não foram criados números históricos fictícios.</div></section>}
function Card({title,value,sub}:{title:string;value:number;sub:string}){return <div className="card"><span>{title}</span><strong>{brl(value)}</strong><small>{sub}</small></div>}
const buttonStyle:React.CSSProperties={border:'1px solid #d0d5dd',background:'#fff',borderRadius:7,padding:'7px 10px',fontSize:12,color:'#344054',cursor:'pointer'}
const selectStyle:React.CSSProperties={border:'1px solid #dbe1e8',background:'#fff',borderRadius:8,padding:'8px 10px',color:'#172033',fontSize:12,minWidth:120}
