import { closingEngine } from '@/lib/closing-engine'

export default function FechamentoContabil(){
 const c=closingEngine()
 const status=(ok:boolean)=>ok?'✓ OK':'! REVISAR'
 return <main className="content" style={{marginLeft:0,width:'100%',maxWidth:1400,margin:'0 auto'}}><header><div><small>CONTROLADORIA • FECHAMENTO</small><h1>Fechamento Contábil</h1><p>Validação cruzada entre BP, DRE, DFC e PL</p></div><div className="period">2026</div></header>
 <div className="cards"><div className="card"><span>Resultado do período</span><strong>{c.result.toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0})}</strong><small>DRE → PL</small></div><div className="card"><span>Equação patrimonial</span><strong>{status(c.checks.bp)}</strong><small>Ativo = Passivo + PL</small></div><div className="card"><span>Conciliação de caixa</span><strong>{status(c.checks.cash)}</strong><small>DFC = Caixa</small></div><div className="card"><span>Fechamento geral</span><strong>{status(c.checks.overall)}</strong><small>Controles principais</small></div></div>
 <section className="panel wide"><div className="panel-title"><h2>Checklist de fechamento</h2><span>{c.checks.overall?'Fechamento consistente':'Pendências'}</span></div><div className="check"><i className={c.checks.bp?'ok':'bad'}>{c.checks.bp?'✓':'!'}</i><div><b>1. Balanço Patrimonial</b><small>Diferença Ativo − (Passivo + PL): {c.bpDifference.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</small></div></div><div className="check"><i className={c.checks.cash?'ok':'bad'}>{c.checks.cash?'✓':'!'}</i><div><b>2. DFC × Caixa</b><small>Diferença entre Caixa Final calculado e saldo do Razão: {c.cashDifference.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</small></div></div><div className="check"><i className={c.checks.result?'ok':'bad'}>{c.checks.result?'✓':'!'}</i><div><b>3. Resultado do período</b><small>Receitas − Custos − Despesas = {c.result.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</small></div></div></section>
 <section className="panel"><div className="panel-title"><h2>Ponte do Patrimônio Líquido</h2><span>DMPL</span></div><div className="note">O resultado apurado na DRE deve ser refletido na movimentação do Patrimônio Líquido. O saldo de <strong>Lucros Acumulados</strong> é patrimonial; ele não é automaticamente igual ao Lucro Líquido do período.</div><div className="rows"><div className="row"><span>Resultado do período</span><b>{c.result.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</b></div><div className="row"><span>PL após resultado (sem outras movimentações)</span><b>{c.dmplExpected.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</b></div></div></section>
 </main>
}
