'use client'
import { useMemo, useState } from 'react'
import { openReceivablesPayables, agingSummary, type OpenItem } from '@/lib/contas-receber-pagar'
import { readFinancialSource } from '@/lib/financial-source'
const brl=(n:number)=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0})
export default function ContasReceberPagar(){
 const [asOf,setAsOf]=useState('2026-12-31'); const [expanded,setExpanded]=useState<Set<string>>(new Set()); const entries=readFinancialSource().entries
 const items=useMemo(()=>openReceivablesPayables(entries,asOf),[entries,asOf]); const summary=agingSummary(items)
 const receivable=items.filter(i=>i.direction==='Receber').reduce((s,i)=>s+Math.abs(i.value),0); const payable=items.filter(i=>i.direction==='Pagar').reduce((s,i)=>s+Math.abs(i.value),0); const overdue=items.filter(i=>i.daysOverdue>0); const overdueRecv=overdue.filter(i=>i.direction==='Receber').reduce((s,i)=>s+Math.abs(i.value),0)
 const toggle=(k:string)=>setExpanded(p=>{const n=new Set(p);n.has(k)?n.delete(k):n.add(k);return n})
 return <main className="content" style={{marginLeft:0,width:'100%',maxWidth:1500,margin:'0 auto'}}><header><div><small>CAPITAL DE GIRO</small><h1>Contas a Receber & Pagar</h1><p>Liquidez • Aging • Vencimentos • Cobrança • Obrigações</p></div><div className="period-controls"><label>Data-base</label><input type="date" value={asOf} onChange={e=>setAsOf(e.target.value)}/></div></header>
 <div className="cards"><Card title="A Receber" value={receivable} sub="Títulos em aberto"/><Card title="A Pagar" value={payable} sub="Obrigações em aberto"/><Card title="Inadimplente" value={overdueRecv} sub="Recebíveis vencidos"/><Card title="Títulos" value={items.length} sub="Em aberto" currency={false}/></div>
 <section className="panel wide"><div className="panel-title"><div><h2>Mapa de Aging</h2><span>+ expande • − recolhe • clique no grupo para detalhar</span></div><span>Data-base {new Date(`${asOf}T00:00:00`).toLocaleDateString('pt-BR')}</span></div><div className="table-wrap"><table><thead><tr><th style={{textAlign:'left'}}>Faixa</th><th>A Receber</th><th>A Pagar</th><th>Saldo líquido</th></tr></thead><tbody>{summary.map(s=>{const key=s.aging;const open=expanded.has(key);const rows=items.filter(x=>x.aging===key);return <><tr key={key} className="group-row" onClick={()=>toggle(key)} style={{cursor:'pointer'}}><td><ExpandIcon open={open} onClick={()=>toggle(key)} label={key}/><b>{key}</b></td><td>{brl(s.receber)}</td><td>{brl(s.pagar)}</td><td><b>{brl(s.receber-s.pagar)}</b></td></tr>{open&&rows.map(item=><ItemRow key={item.id} item={item}/>)}</>})}</tbody></table></div></section>
 <div className="grid"><section className="panel"><div className="panel-title"><h2>Recebíveis críticos</h2><span>{overdue.filter(i=>i.direction==='Receber').length} título(s)</span></div><div className="rows">{overdue.filter(i=>i.direction==='Receber').sort((a,b)=>b.daysOverdue-a.daysOverdue).slice(0,8).map(i=><ItemCompact key={i.id} item={i}/>)}</div>{!overdue.some(i=>i.direction==='Receber')&&<div className="note">Nenhum recebível vencido na data-base.</div>}</section><section className="panel"><div className="panel-title"><h2>Obrigações críticas</h2><span>{overdue.filter(i=>i.direction==='Pagar').length} título(s)</span></div><div className="rows">{overdue.filter(i=>i.direction==='Pagar').sort((a,b)=>b.daysOverdue-a.daysOverdue).slice(0,8).map(i=><ItemCompact key={i.id} item={i}/>)}</div>{!overdue.some(i=>i.direction==='Pagar')&&<div className="note">Nenhuma obrigação vencida na data-base.</div>}</section></div>
 <section className="panel wide"><div className="panel-title"><h2>Leitura gerencial</h2><span>Ação</span></div><div className="grid"><div className="note"><strong>Contas a receber</strong><p>{brl(receivable)} em aberto. Recebíveis vencidos somam {brl(overdueRecv)}.</p></div><div className="note"><strong>Contas a pagar</strong><p>{brl(payable)} em obrigações em aberto. Use o aging para priorizar caixa e negociação.</p></div><div className="note"><strong>Próximo impacto</strong><p>Esta visão será usada pelo Capital de Giro e Fluxo de Caixa para melhorar a previsão de entradas e saídas.</p></div></div></section></main>
}
function ItemRow({item}:{item:OpenItem}){return <tr className="item-row"><td style={{paddingLeft:34}}>↳ {item.description}</td><td>{item.direction==='Receber'?brl(Math.abs(item.value)):'—'}</td><td>{item.direction==='Pagar'?brl(Math.abs(item.value)):'—'}</td><td>{item.dueDate} • {item.category}</td></tr>}
function ItemCompact({item}:{item:OpenItem}){return <div className="row"><span><b>{item.description}</b><small style={{display:'block',color:'#667085'}}>{item.category} • vencimento {item.dueDate} • {item.daysOverdue} dias</small></span><b>{brl(Math.abs(item.value))}</b></div>}
function ExpandIcon({open,onClick,label}:{open:boolean;onClick:()=>void;label:string}){return <button type="button" className="expand-btn" aria-label={open?`Recolher ${label}`:`Expandir ${label}`} onClick={e=>{e.stopPropagation();onClick()}}>{open?'−':'+'}</button>}
function Card({title,value,sub,currency=true}:{title:string;value:number;sub:string;currency?:boolean}){return <div className="card"><span>{title}</span><strong>{currency?brl(value):value.toLocaleString('pt-BR')}</strong><small>{sub}</small></div>}
