'use client'
import {useMemo,useState} from 'react'
import {openReceivablesPayables,agingSummary,type OpenItem} from '@/lib/contas-receber-pagar'
import {readFinancialSource} from '@/lib/financial-source'
import {financialCore} from '@/lib/financial-core'
import ReportPeriodFilter from '@/components/report-period-filter'
import {DEFAULT_REPORT_PERIOD,competence} from '@/lib/report-period'
import type {ReportPeriod} from '@/lib/report-period'
const brl=(n:number)=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0})
const pct=(n:number)=>`${(n*100).toFixed(1).replace('.',',')}%`
const endOfMonth=(y:number,m:number)=>new Date(y,m,0).toISOString().slice(0,10)
const timing=(i:OpenItem)=>i.daysOverdue>0?`Vencido há ${i.daysOverdue} dia(s)`:`Vence em ${i.daysToDue} dia(s)`
export default function ContasReceberPagar(){
 const [period,setPeriod]=useState<ReportPeriod>({...DEFAULT_REPORT_PERIOD,month:12}); const [expanded,setExpanded]=useState<Set<string>>(new Set()); const [detail,setDetail]=useState<string|null>(null)
 const entries=useMemo(()=>readFinancialSource().entries,[]); const asOf=endOfMonth(period.year,period.month)
 const items=useMemo(()=>openReceivablesPayables(entries,asOf),[entries,asOf]); const summary=agingSummary(items)
 const previous=useMemo(()=>{const y=period.month===1?period.year-1:period.year;const m=period.month===1?12:period.month-1;return openReceivablesPayables(entries,endOfMonth(y,m))},[entries,period.year,period.month])
 const total=(dir:'Receber'|'Pagar',list=items)=>list.filter(i=>i.direction===dir).reduce((s,i)=>s+Math.abs(i.value),0)
 const receivable=total('Receber'),payable=total('Pagar'); const overdue=items.filter(i=>i.daysOverdue>0); const overdueRecv=total('Receber',overdue); const overduePay=total('Pagar',overdue)
 const prevRecv=total('Receber',previous),prevPay=total('Pagar',previous); const core=financialCore[Math.min(financialCore.length-1,period.month-1)]; const coreRecv=core?.accountsReceivable||0,corePay=core?.suppliers||0
 const shown=period.view==='comparativo'?previous:items; const groups=agingSummary(shown)
 const concentration=useMemo(()=>{const m=new Map<string,{name:string;dir:string;value:number;count:number}>();items.forEach(i=>{const k=`${i.direction}|${i.description}`,o=m.get(k);m.set(k,{name:i.description,dir:i.direction,value:(o?.value||0)+Math.abs(i.value),count:(o?.count||0)+1})});return [...m.values()].sort((a,b)=>b.value-a.value).slice(0,8)},[items])
 const toggle=(k:string)=>setExpanded(p=>{const n=new Set(p);n.has(k)?n.delete(k):n.add(k);return n})
 return <main className="content" style={{marginLeft:0,width:'100%',maxWidth:1500,margin:'0 auto'}}><header><div><small>CAPITAL DE GIRO</small><h1>Contas a Receber & Pagar</h1><p>Liquidez • Aging • Vencimentos • Cobrança • Obrigações</p></div><ReportPeriodFilter value={period} onChange={p=>{setPeriod(p);setExpanded(new Set());setDetail(null)}} years={[2026]}/></header>
 <div className="cards"><Card title="A Receber" value={receivable} sub="Títulos em aberto"/><Card title="A Pagar" value={payable} sub="Obrigações em aberto"/><Card title="Inadimplente" value={overdueRecv} sub={`${pct(receivable?overdueRecv/receivable:0)} do a receber`}/><Card title="Vencidos" value={overdueRecv+overduePay} sub={`${overdue.length} título(s)`}/></div>
 {period.view==='comparativo'&&<section className="panel wide"><div className="panel-title"><h2>Comparativo</h2><span>{period.month===1?`Dez/${period.year-1}`:`mês anterior`} × {period.month}/{period.year}</span></div><div className="grid"><Compare title="A Receber" value={receivable} previous={prevRecv}/><Compare title="A Pagar" value={payable} previous={prevPay}/><Compare title="Saldo líquido" value={receivable-payable} previous={prevRecv-prevPay}/></div></section>}
 <section className="panel wide"><div className="panel-title"><div><h2>Conciliação com o Balanço Patrimonial</h2><span>Data-base: {asOf} • títulos × saldo contábil</span></div><span>{Math.abs(coreRecv-receivable)<.01&&Math.abs(corePay-payable)<.01?'RECONCILIADO':'ATENÇÃO'}</span></div><div className="grid"><Recon title="Contas a Receber" detail={receivable} accounting={coreRecv}/><Recon title="Fornecedores" detail={payable} accounting={corePay}/></div></section>
 <section className="panel wide"><div className="panel-title"><h2>Mapa de Aging</h2><span>{period.view==='acumulado'?'Acumulado até ':''}{asOf}</span></div><div className="table-wrap"><table><thead><tr><th>Faixa</th><th>A Receber</th><th>A Pagar</th><th>Saldo líquido</th></tr></thead><tbody>{groups.map(g=>{const open=expanded.has(g.aging);return <><tr key={g.aging} className="group-row" onClick={()=>toggle(g.aging)}><td><button type="button" className="expand-btn">{open?'−':'+'}</button><b>{g.aging}</b></td><td>{brl(g.receber)}</td><td>{brl(g.pagar)}</td><td><b>{brl(g.receber-g.pagar)}</b></td></tr>{open&&shown.filter(i=>i.aging===g.aging).map(i=><tr key={i.id} className="item-row" onClick={()=>setDetail(String(i.id))}><td style={{paddingLeft:34}}>↳ {i.description}</td><td>{i.direction==='Receber'?brl(Math.abs(i.value)):'—'}</td><td>{i.direction==='Pagar'?brl(Math.abs(i.value)):'—'}</td><td>{i.dueDate} • {timing(i)}</td></tr>)}</>})}</tbody></table></div>{detail&&<Detail item={shown.find(i=>String(i.id)===detail)||null} close={()=>setDetail(null)}/>}</section>
 <div className="grid"><section className="panel"><div className="panel-title"><h2>Concentração</h2><span>Top 8</span></div><div className="rows">{concentration.map((c,i)=><div className="row" key={`${c.dir}-${c.name}`}><span><b>{i+1}. {c.name}</b><small>{c.dir} • {c.count} título(s)</small></span><b>{brl(c.value)}</b></div>)}</div></section><section className="panel"><div className="panel-title"><h2>Risco de vencimento</h2><span>Prioridade</span></div><div className="rows">{summary.map(s=><div className="row" key={s.aging}><span>{s.aging}</span><b>{brl(s.receber+s.pagar)}</b></div>)}</div><div className="note"><strong>Leitura:</strong> {overdue.length?`${brl(overdueRecv+overduePay)} está vencido.`:'não há títulos vencidos na data-base.'}</div></section></div>
 <section className="panel wide"><div className="panel-title"><h2>Próximos vencimentos</h2><span>7 / 30 / 60 dias</span></div><div className="grid"><Due title="7 dias" items={items.filter(i=>i.daysToDue>0&&i.daysToDue<=7)}/><Due title="30 dias" items={items.filter(i=>i.daysToDue>0&&i.daysToDue<=30)}/><Due title="60 dias" items={items.filter(i=>i.daysToDue>0&&i.daysToDue<=60)}/></div></section></main>
}
function Card({title,value,sub}:{title:string;value:number;sub:string}){return <div className="card"><span>{title}</span><strong>{brl(value)}</strong><small>{sub}</small></div>}
function Compare({title,value,previous}:{title:string;value:number;previous:number}){const v=previous?(value-previous)/Math.abs(previous):0;return <div className="card"><span>{title}</span><strong>{brl(value)}</strong><small>vs. mês anterior: {v>=0?'+':''}{(v*100).toFixed(1).replace('.',',')}%</small></div>}
function Recon({title,detail,accounting}:{title:string;detail:number;accounting:number}){const d=accounting-detail;return <div className="note"><div className="row"><strong>{title}</strong><b>{Math.abs(d)<.01?'OK':'PARCIAL'}</b></div><div className="row"><span>Títulos em aberto</span><b>{brl(detail)}</b></div><div className="row"><span>Saldo contábil</span><b>{brl(accounting)}</b></div><div className="row"><span>Diferença</span><b>{brl(d)}</b></div></div>}
function Due({title,items}:{title:string;items:OpenItem[]}){const r=items.filter(i=>i.direction==='Receber').reduce((s,i)=>s+Math.abs(i.value),0),p=items.filter(i=>i.direction==='Pagar').reduce((s,i)=>s+Math.abs(i.value),0);return <div className="note"><strong>{title}</strong><div className="row"><span>A receber</span><b>{brl(r)}</b></div><div className="row"><span>A pagar</span><b>{brl(p)}</b></div><div className="row"><span>Saldo</span><b>{brl(r-p)}</b></div><small>{items.length} título(s)</small></div>}
function Detail({item,close}:{item:OpenItem|null;close:()=>void}){if(!item)return null;return <div className="note" style={{marginTop:12}}><strong>Detalhamento</strong><p>{item.description} • {item.direction}</p><small>{item.category} • {item.costCenter} • competência {item.competence} • vencimento {item.dueDate} • {timing(item)} • {brl(Math.abs(item.value))}</small><br/><button type="button" onClick={close}>Fechar</button></div>}
