'use client'
import { useMemo, useState } from 'react'
import { openReceivablesPayables, agingSummary, type OpenItem } from '@/lib/contas-receber-pagar'
import { readFinancialSource } from '@/lib/financial-source'
import { financialCore } from '@/lib/financial-core'
const brl=(n:number)=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0})
const pct=(n:number)=>`${(n*100).toFixed(1).replace('.',',')}%`
const timing=(item:OpenItem)=>item.daysOverdue>0?`Vencido há ${item.daysOverdue} dia(s)`:`Vence em ${item.daysToDue} dia(s)`
export default function ContasReceberPagar(){
 const [asOf,setAsOf]=useState('2026-12-31'); const [expanded,setExpanded]=useState<Set<string>>(new Set()); const [detail,setDetail]=useState<string|null>(null); const entries=readFinancialSource().entries
 const items=useMemo(()=>openReceivablesPayables(entries,asOf),[entries,asOf]); const summary=agingSummary(items)
 const receivable=items.filter(i=>i.direction==='Receber').reduce((s,i)=>s+Math.abs(i.value),0); const payable=items.filter(i=>i.direction==='Pagar').reduce((s,i)=>s+Math.abs(i.value),0); const overdue=items.filter(i=>i.daysOverdue>0); const overdueRecv=overdue.filter(i=>i.direction==='Receber').reduce((s,i)=>s+Math.abs(i.value),0); const overduePay=overdue.filter(i=>i.direction==='Pagar').reduce((s,i)=>s+Math.abs(i.value),0)
 const coreIndex=Math.max(0,Math.min(financialCore.length-1,Number(asOf.slice(5,7))-1)); const coreMonth=financialCore[coreIndex]; const coreReceivable=coreMonth?.accountsReceivable||0; const coreSuppliers=coreMonth?.suppliers||0; const receivableGap=coreReceivable-receivable; const payableGap=coreSuppliers-payable; const receivableReconciled=Math.abs(receivableGap)<0.01; const payableReconciled=Math.abs(payableGap)<0.01
 const toggle=(k:string)=>setExpanded(p=>{const n=new Set(p);n.has(k)?n.delete(k):n.add(k);return n})
 const concentration=useMemo(()=>{const map=new Map<string,{name:string;direction:string;value:number;count:number}>();items.forEach(i=>{const key=`${i.direction}|${i.description}`;const old=map.get(key);map.set(key,{name:i.description,direction:i.direction,value:(old?.value||0)+Math.abs(i.value),count:(old?.count||0)+1})});return Array.from(map.values()).sort((a,b)=>b.value-a.value).slice(0,8)},[items])
 const totalOverdue=overdueRecv+overduePay; const overdueRate=items.length?(overdue.length/items.length):0
 return <main className="content" style={{marginLeft:0,width:'100%',maxWidth:1500,margin:'0 auto'}}><header><div><small>CAPITAL DE GIRO</small><h1>Contas a Receber & Pagar</h1><p>Liquidez • Aging • Vencimentos • Cobrança • Obrigações</p></div><div className="period-controls"><label>Data-base</label><input type="date" value={asOf} onChange={e=>{setAsOf(e.target.value);setExpanded(new Set());setDetail(null)}}/></div></header>
 <div className="cards"><Card title="A Receber" value={receivable} sub="Títulos em aberto"/><Card title="A Pagar" value={payable} sub="Obrigações em aberto"/><Card title="Inadimplente" value={overdueRecv} sub={`${pct(receivable?overdueRecv/receivable:0)} do a receber`}/><Card title="Vencidos" value={totalOverdue} sub={`${overdue.length} título(s) • ${pct(overdueRate)} da carteira`}/></div>
 <section className="panel wide"><div className="panel-title"><div><h2>Conciliação com o Balanço Patrimonial</h2><span>Detalhamento de títulos × saldo contábil • sem criar lançamentos artificiais</span></div><span>{receivableReconciled&&payableReconciled?'RECONCILIADO':'ATENÇÃO'}</span></div><div className="grid"><ReconciliationCard title="Contas a Receber" detail={receivable} accounting={coreReceivable} difference={receivableGap} reconciled={receivableReconciled} note="Saldo contábil de Contas a Receber no Financial Core."/><ReconciliationCard title="Fornecedores" detail={payable} accounting={coreSuppliers} difference={payableGap} reconciled={payableReconciled} note="Saldo contábil de Fornecedores no Financial Core."/></div><div className="note" style={{marginTop:12}}><strong>Leitura:</strong> o Aging detalha somente títulos operacionais em aberto. Qualquer diferença para o saldo contábil permanece explicitamente identificada como saldo ainda não detalhado, evitando que o sistema trate uma carteira parcial como se fosse o total do BP.</div></section>
 <section className="panel wide"><div className="panel-title"><div><h2>Mapa de Aging</h2><span>+ expande • − recolhe • grupo → título → lançamento</span></div><span>Data-base {new Date(`${asOf}T00:00:00`).toLocaleDateString('pt-BR')}</span></div><div className="table-wrap"><table><thead><tr><th style={{textAlign:'left'}}>Faixa</th><th>A Receber</th><th>A Pagar</th><th>Saldo líquido</th></tr></thead><tbody>{summary.map(s=>{const key=s.aging;const open=expanded.has(key);const rows=items.filter(x=>x.aging===key);return <>{<tr key={key} className="group-row" onClick={()=>toggle(key)} style={{cursor:'pointer'}}><td><ExpandIcon open={open} onClick={()=>toggle(key)} label={key}/><b>{key}</b></td><td>{brl(s.receber)}</td><td>{brl(s.pagar)}</td><td><b>{brl(s.receber-s.pagar)}</b></td></tr>}{open&&rows.map(item=><ItemRow key={item.id} item={item} onDetail={()=>setDetail(String(item.id))} active={detail===String(item.id)}/>)}</>})}</tbody></table></div>{detail&&<Detail item={items.find(i=>String(i.id)===detail)||null} onClose={()=>setDetail(null)}/>}</section>
 <div className="grid"><section className="panel"><div className="panel-title"><h2>Concentração por cliente / fornecedor</h2><span>Top 8 • pela descrição do lançamento</span></div><div className="rows">{concentration.map((c,i)=><div className="row" key={`${c.direction}-${c.name}`}><span><b>{i+1}. {c.name}</b><small style={{display:'block',color:'#667085'}}>{c.direction} • {c.count} título(s)</small></span><b>{brl(c.value)}</b></div>)}</div>{!concentration.length&&<div className="note">Nenhum título em aberto na data-base.</div>}</section><section className="panel"><div className="panel-title"><h2>Risco de vencimento</h2><span>Prioridade</span></div><div className="aging-bars">{summary.map(s=>{const total=s.receber+s.pagar;const width=Math.max(total?4:0,Math.min(100,total/(receivable+payable||1)*100));return <div className="aging-bar" key={s.aging}><div><span>{s.aging}</span><b>{brl(total)}</b></div><div className="bar-track"><i style={{width:`${width}%`}}/></div></div>})}</div><div className="note" style={{marginTop:12}}><strong>Leitura:</strong> {overdue.length?`${brl(totalOverdue)} está vencido, sendo ${brl(overdueRecv)} a receber e ${brl(overduePay)} a pagar.`:'não há títulos vencidos na data-base.'}</div></section></div>
 <div className="grid"><section className="panel"><div className="panel-title"><h2>Recebíveis críticos</h2><span>{overdue.filter(i=>i.direction==='Receber').length} título(s)</span></div><div className="rows">{overdue.filter(i=>i.direction==='Receber').sort((a,b)=>b.daysOverdue-a.daysOverdue).slice(0,8).map(i=><ItemCompact key={i.id} item={i} onClick={()=>setDetail(String(i.id))}/>)}</div>{!overdue.some(i=>i.direction==='Receber')&&<div className="note">Nenhum recebível vencido na data-base.</div>}</section><section className="panel"><div className="panel-title"><h2>Obrigações críticas</h2><span>{overdue.filter(i=>i.direction==='Pagar').length} título(s)</span></div><div className="rows">{overdue.filter(i=>i.direction==='Pagar').sort((a,b)=>b.daysOverdue-a.daysOverdue).slice(0,8).map(i=><ItemCompact key={i.id} item={i} onClick={()=>setDetail(String(i.id))}/>)}</div>{!overdue.some(i=>i.direction==='Pagar')&&<div className="note">Nenhuma obrigação vencida na data-base.</div>}</section></div>
 <section className="panel wide"><div className="panel-title"><h2>Próximos vencimentos</h2><span>Visão de caixa • 7 / 30 / 60 dias</span></div><div className="grid"><DueWindow title="Próximos 7 dias" items={items.filter(i=>i.daysToDue>0&&i.daysToDue<=7)}/><DueWindow title="Próximos 30 dias" items={items.filter(i=>i.daysToDue>0&&i.daysToDue<=30)}/><DueWindow title="Próximos 60 dias" items={items.filter(i=>i.daysToDue>0&&i.daysToDue<=60)}/></div></section>
 <section className="panel wide"><div className="panel-title"><h2>Leitura gerencial</h2><span>Ação</span></div><div className="grid"><div className="note"><strong>Contas a receber</strong><p>{brl(receivable)} em aberto. Recebíveis vencidos somam {brl(overdueRecv)}.</p></div><div className="note"><strong>Contas a pagar</strong><p>{brl(payable)} em obrigações em aberto. Use o aging para priorizar caixa e negociação.</p></div><div className="note"><strong>Próximo impacto</strong><p>O aging agora mostra quando os títulos devem entrar ou sair do caixa, além do atraso já ocorrido.</p></div></div></section></main>
}
function ReconciliationCard({title,detail,accounting,difference,reconciled,note}:{title:string;detail:number;accounting:number;difference:number;reconciled:boolean;note:string}){return <div className="note" style={{border:`1px solid ${reconciled?'#b7e4c7':'#f0c36a'}`}}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><strong>{title}</strong><b>{reconciled?'OK':'PARCIAL'}</b></div><div className="row" style={{marginTop:10}}><span>Títulos em aberto</span><b>{brl(detail)}</b></div><div className="row"><span>Saldo contábil</span><b>{brl(accounting)}</b></div><div className="row"><span>Diferença</span><b>{brl(difference)}</b></div><small>{note}</small></div>}
function DueWindow({title,items}:{title:string;items:OpenItem[]}){const receive=items.filter(i=>i.direction==='Receber').reduce((s,i)=>s+Math.abs(i.value),0);const pay=items.filter(i=>i.direction==='Pagar').reduce((s,i)=>s+Math.abs(i.value),0);return <div className="note"><strong>{title}</strong><div style={{marginTop:8}}><div className="row"><span>A receber</span><b>{brl(receive)}</b></div><div className="row"><span>A pagar</span><b>{brl(pay)}</b></div><div className="row"><span>Saldo potencial</span><b>{brl(receive-pay)}</b></div><small>{items.length} título(s)</small></div></div>}
function ItemRow({item,onDetail,active}:{item:OpenItem;onDetail:()=>void;active:boolean}){return <tr className="item-row" style={{cursor:'pointer',background:active?'#eef5ff':undefined}} onClick={onDetail}><td style={{paddingLeft:34}}>↳ {item.description}</td><td>{item.direction==='Receber'?brl(Math.abs(item.value)):'—'}</td><td>{item.direction==='Pagar'?brl(Math.abs(item.value)):'—'}</td><td>{item.dueDate} • {timing(item)} • {item.category}</td></tr>}
function ItemCompact({item,onClick}:{item:OpenItem;onClick:()=>void}){return <div className="row" style={{cursor:'pointer'}} onClick={onClick}><span><b>{item.description}</b><small style={{display:'block',color:'#667085'}}>{item.category} • vencimento {item.dueDate} • {timing(item)}</small></span><b>{brl(Math.abs(item.value))}</b></div>}
function Detail({item,onClose}:{item:OpenItem|null;onClose:()=>void}){if(!item)return null;return <div className="note" style={{marginTop:12,border:'1px solid #cbd8e8'}}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><strong>Detalhamento do título</strong><p style={{marginBottom:4}}>{item.description} • {item.direction}</p><small>Categoria: {item.category} • Centro de custo: {item.costCenter} • Competência: {item.competence} • Vencimento: {item.dueDate} • {timing(item)} • Aging: {item.aging} • Valor: {brl(Math.abs(item.value))}</small></div><button type="button" onClick={onClose} style={{height:32,padding:'0 10px',border:'1px solid #d0d5dd',borderRadius:8,background:'#fff',cursor:'pointer'}}>Fechar</button></div></div>}
function ExpandIcon({open,onClick,label}:{open:boolean;onClick:()=>void;label:string}){return <button type="button" className="expand-btn" aria-label={open?`Recolher ${label}`:`Expandir ${label}`} onClick={e=>{e.stopPropagation();onClick()}}>{open?'−':'+'}</button>}
function Card({title,value,sub,currency=true}:{title:string;value:number;sub:string;currency?:boolean}){return <div className="card"><span>{title}</span><strong>{currency?brl(value):value.toLocaleString('pt-BR')}</strong><small>{sub}</small></div>}
